### ISSUE TITLE
setup.py failed when third_party directory removed

### ISSUE THREAD

**Issue by picca** [kif/fabio#23]
Hello, when preparing the debian package, I remove the third_party to avoid embeding code.
But then during the build, the process stoped with 

copying fabio-src/pnmimage.py -> /tmp/buildd/python-fabio-0.2.1+dfsg1/.pybuild/pythonX.Y_2.7/build/fabio
error: package directory 'third_party' does not exist
E: pybuild pybuild:256: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 
dh_auto_build: pybuild --build -i python{version} -p 2.7 --dir . returned exit code 13
debian/rules:22: recipe for target 'override_dh_auto_build-indep' failed

Is it possible to fix the seup.py to check for the third_party directory existance ?
Then I will add the right dependencies for argparses,six etc...

thanks

Fred

**Comment by picca** [comment]
Once not installedm I get this error

Traceback (most recent call last):
  File "test_all.py", line 16, in <module>
    logger = utilstest.UtilsTest.get_logger(__file__)
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/test/utilstest.py", line 367, in get_logger
    UtilsTest.forceBuild(force_remove)
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/test/utilstest.py", line 185, in forceBuild
    cls.fabio = cls.deep_reload()
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/test/utilstest.py", line 159, in deep_reload
    cls.fabio = __import__(cls.name)
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/.pybuild/pythonX.Y_2.7/build/fabio/__init__.py", line 18, in <module>
    from . import fabioimage
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/.pybuild/pythonX.Y_2.7/build/fabio/fabioimage.py", line 25, in <module>
    from . import fabioutils, converters
  File "/tmp/buildd/python-fabio-0.2.1+dfsg1/.pybuild/pythonX.Y_2.7/build/fabio/fabioutils.py", line 18, in <module>
    from .third_party import six
ImportError: No module named third_party

**Comment by kif** [comment]
On Sun, 22 Mar 2015 02:15:44 -0700
picca <notifications@github.com> wrote:

> Hello, when preparing the debian package, I remove the third_party to avoid embeding code.

The third party directory has been created to separate "external" code from our own one. This is also why a "copyright" file has been added to ease the distribution.

It is not intended to be removed:
* gzip module has been adapted from Python2.7. The one from 2.7 would break installation of fabio on python3 systems.
* TiffIO comes from pymca (which would create a dependency on qhull, mesa, pymca-data ...

I wonder if it makes much sense.

-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by kif** [comment]
On Sun, 22 Mar 2015 03:25:19 -0700
picca <notifications@github.com> wrote:

> Once not installedm I get this error
> 
> ImportError: No module named third_party

the problem will be the same with:

fabio-src/cbfimage.py:from .third_party import six
fabio-src/compression.py:from .third_party import six
fabio-src/compression.py:        from .third_party import gzip
fabio-src/edfimage.py:from .third_party import six
fabio-src/fabioutils.py:from .third_party import six
fabio-src/kcdimage.py:from .third_party import six
fabio-src/pnmimage.py:from .third_party import six
fabio-src/tifimage.py:from .third_party.TiffIO import TiffIO
fabio-src/xsdimage.py:from .third_party import six

one would need to do 

try:
   import six
   if tuple(int(i) for i in six.__version__.split(".")[:3])<(1,8,0):
       raise Importerror("Six version is too old")
except ImportError:
   from .third_party import six.


-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>
