### ISSUE TITLE
offer iterator

### ISSUE THREAD

**Issue by kif** [kif/fabio#29]
There is a memory management issue with large multiframe EDF images.

Offering an iterator over them (with explicit destruction of data) would solve it.

**Comment by jonwright** [comment]
Hi Jerome, 
Can you make it work for users of fabio.file_series.new_file_series please?
Thanks!

**Comment by t20100** [comment]
Here is a monkey-patch to add an iterator to fabioimage:

```python
import fabio

def __fabio__iter__(self):
    current_image = self
    while True:
        yield current_image
        try:
            current_image = current_image.next()
        except IOError:
            raise StopIteration
fabio.fabioimage.fabioimage.__iter__ = __fabio__iter__
```
