### ISSUE TITLE
In order to facilitate the copyright file generation it would be nice to add the licenses header in each files

### ISSUE THREAD

**Issue by picca** [kif/fabio#31]
doc/source/conf.py: *No copyright* GENERATED FILE
fabio-src/raxisimage.py: *No copyright* UNKNOWN
fabio-src/_version.py: *No copyright* UNKNOWN
fabio-src/openimage.py: *No copyright* UNKNOWN
fabio-src/marccdimage.py: *No copyright* UNKNOWN
fabio-src/__init__.py: *No copyright* UNKNOWN
fabio-src/pilatusimage.py: *No copyright* UNKNOWN
fabio-src/fit2dspreadsheetimage.py: *No copyright* UNKNOWN
fabio-src/pixiimage.py: *No copyright* UNKNOWN
fabio-src/edfimage.py: *No copyright* UNKNOWN
fabio-src/adscimage.py: *No copyright* UNKNOWN
fabio-src/GEimage_old.py: *No copyright* UNKNOWN
fabio-src/OXDimage.py: *No copyright* UNKNOWN
fabio-src/mar345image.py: *No copyright* UNKNOWN
fabio-src/xsdimage.py: *No copyright* UNKNOWN
fabio-src/directories.py: *No copyright* UNKNOWN
fabio-src/converters.py: *No copyright* UNKNOWN
fabio-src/nexus.py: GPL (v3 or later)
fabio-src/mrcimage.py: *No copyright* UNKNOWN
fabio-src/GEimage.py: *No copyright* UNKNOWN
fabio-src/templateimage.py: *No copyright* UNKNOWN
fabio-src/readbytestream.py: *No copyright* UNKNOWN
fabio-src/brukerimage.py: *No copyright* UNKNOWN
fabio-src/tifimage.py: UNKNOWN
fabio-src/fabioimage.py: *No copyright* UNKNOWN
fabio-src/bruker100image.py: *No copyright* UNKNOWN
fabio-src/cbfimage.py: *No copyright* GENERATED FILE
fabio-src/compression.py: *No copyright* UNKNOWN
fabio-src/hdf5image.py: *No copyright* UNKNOWN
fabio-src/dm3image.py: *No copyright* UNKNOWN
fabio-src/kcdimage.py: *No copyright* UNKNOWN
fabio-src/fit2dmaskimage.py: *No copyright* UNKNOWN
fabio-src/file_series.py: *No copyright* UNKNOWN
fabio-src/datIO.py: *No copyright* UNKNOWN
fabio-src/fabioutils.py: *No copyright* UNKNOWN
fabio-src/HiPiCimage.py: *No copyright* UNKNOWN
fabio-src/binaryimage.py: *No copyright* UNKNOWN
fabio-src/pnmimage.py: *No copyright* UNKNOWN
setup.py: *No copyright* GENERATED FILE
src/stdint.h: BSD (2 clause)
src/columnfile.c: *No copyright* UNKNOWN
src/ccp4_pack.c: LGPL (v3 or later)
src/mar345_IO.pyx: *No copyright* UNKNOWN
src/columnfile.h: *No copyright* UNKNOWN
src/ccp4_pack.h: LGPL (v3 or later)
src/cf_io.pyx: *No copyright* UNKNOWN
src/cf_iomodule.c: *No copyright* UNKNOWN
src/byte_offset.pyx: *No copyright* UNKNOWN
src/_cif.pyx: *No copyright* UNKNOWN
test/testtifimage.py: *No copyright* UNKNOWN
test/__init__.py: GPL (v3 or later)
test/testadscimage.py: *No copyright* UNKNOWN
test/test_flat_binary.py: *No copyright* UNKNOWN
test/testGEimage.py: *No copyright* UNKNOWN
test/benchheader.py: *No copyright* UNKNOWN
test/testcbfimage.py: *No copyright* UNKNOWN
test/testopenheader.py: *No copyright* UNKNOWN
test/testfilenames.py: *No copyright* UNKNOWN
test/utilstest.py: UNKNOWN
test/testkcdimage.py: *No copyright* UNKNOWN
test/testOXDimage.py: *No copyright* UNKNOWN
test/testbruker100image.py: *No copyright* UNKNOWN
test/testedfimage.py: *No copyright* UNKNOWN
test/testfit2dmaskimage.py: *No copyright* UNKNOWN
test/profile_compressed.py: *No copyright* UNKNOWN
test/testcompression.py: *No copyright* UNKNOWN
test/testraxisimage.py: *No copyright* UNKNOWN
test/test_filename_steps.py: *No copyright* UNKNOWN
test/testmccdimage.py: *No copyright* UNKNOWN
test/profile/benchheader.py: *No copyright* UNKNOWN
test/profile/profile_compressed.py: *No copyright* UNKNOWN
test/test_all_images.py: *No copyright* UNKNOWN
test/testfabioimage.py: *No copyright* UNKNOWN
test/testbrukerimage.py: *No copyright* UNKNOWN
test/testheadernotsingleton.py: *No copyright* UNKNOWN
test/testpnmimage.py: *No copyright* UNKNOWN
test/test_all.py: *No copyright* UNKNOWN
test/bug16_ppc64le.py: *No copyright* UNKNOWN
test/test_file_series.py: *No copyright* UNKNOWN
test/testopenimage.py: *No copyright* UNKNOWN
test/testXSDimage.py: *No copyright* UNKNOWN
test/testmar345image.py: *No copyright* UNKNOWN
third_party/six.py: MIT/X11 (BSD like)
third_party/__init__.py: *No copyright* UNKNOWN
third_party/argparse.py: Apache (v2.0)
third_party/gzip.py: *No copyright* UNKNOWN
third_party/TiffIO.py: MIT/X11 (BSD like)

**Comment by kif** [comment]
Most files got now their license header.
They are now on top level !
