### ISSUE TITLE
please move TiffIO from pymca into fabio

### ISSUE THREAD

**Issue by picca** [kif/fabio#32]
for now TIffIO is imported from pymca, so I need to import all pymca during the build of fabio.
Would it be possible to move this TiffIO into fabio and make PyMCa depends on fabio.

this would avoid circular depdencies the day pymca will import fabio for x, y, z, reason.

**Comment by kif** [comment]
The policy we have chosen within the data analysis unit is to give priority to package provided via the third_party directory. If the packager wants to enforce the use of the dependency (to avoid code duplication) he has to:
* remove the file from third_party
* ensure the library is installed using the dependency management of the operating system.
