### ISSUE TITLE
python setup.py debian_testimages does not work

### ISSUE THREAD

**Issue by picca** [kif/fabio#33]
It ends with a 404 error during the images download.

It seems to me that we should add the images in the repository in order to avoid this problem and simplify the code.
nowadays 100 Mo is not a big deal.
This is done only the first time you do the checkout

**Comment by kif** [comment]
On Thu, 23 Jul 2015 01:48:48 -0700
picca <notifications@github.com> wrote:

> It ends with a 404 error during the images download.
> 
> It seems to me that we should add the images in the repository in order to avoid this problem and simplify the code.
> nowadays 100 Mo is not a big deal.
> This is done only the first time you do the checkout

Could you please calculate the time it would take to do such checkout with a 1 MBit/s and 56k link ?

**Comment by picca** [comment]
ok... for now I unactivated all the test in the Debian package

**Comment by picca** [comment]
Ok but maybe the best solution is to create a dedicated fabio-testimages repository and gives fabio test the location of these data
