### ISSUE TITLE
Move testimages out of sourceforge

### ISSUE THREAD

**Issue by kif** [kif/fabio#40]
Sourceforge has become unreliable: it often breaks continuous integration as testimages are not available.

**Comment by jonwright** [comment]
It will be useful to leave a copy behind at sourceforge in case someone looks there when it is working...

**Comment by kif** [comment]
On Fri, 30 Oct 2015 02:02:12 -0700
Jon Wright <notifications@github.com> wrote:

> It will be useful to leave a copy behind at sourceforge in case someone looks there when it is working...

I had a look if it was possible to have multiple sources and chose the
one answering to the pings ...
but having it implemented multi-platform was not trivial (not
mentionning ESRF's politics which forbids the ping on out network)

For now I did not touch anything on the sf side, but I am borred
getting email the test failed because sf is down/too slow.

Cheers,

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
it is implemented and apparently it works.
