### ISSUE TITLE
Problem with .edf files from MAR3450 PSICHE beamline

### ISSUE THREAD

**Issue by Luindil** [kif/fabio#42]
Hei there,

a user of Dioptas just reported a bug when loading edf files from a MAR3450 detector from the PSICHE beamline at SOLEIL. Reading the file with fabio gives:

WARNING:edfimage:Unable to read header size in header_length ;
ByteOrder
ERROR:edfimage:Unable to locate start of the binary section
WARNING:edfimage:no opening {. Corrupt header of EDF file /home/clemens/Downloads/test.edf

And results in a shifted image:
![screenshot from 2015-11-04 13 49 27](https://cloud.githubusercontent.com/assets/4086557/10938479/e3f7cdec-82fa-11e5-8efc-560d62e8d1a1.png)

Fit2D is able to read the file without problems and they told me that it only doesn't work for the highest resolution files. The example file can be downloaded from:

https://uni-koeln.sciebo.de/index.php/s/K5lswUJNVqnMKKT

**Comment by kif** [comment]
On Wed, 04 Nov 2015 04:51:45 -0800
Clemens Prescher <notifications@github.com> wrote:

> Hei there,
> 
> a user of Dioptas just reported a bug when loading edf files from a MAR3450 detector from the PSICHE beamline at SOLEIL. Reading the file with fabio gives:
> 

Hi Clemens,

Thanks for the report. The header size is reported as "header_size" (and not actually its size).
In this specific case I can fix it quicky.

Anyway for a "mar345" they have a compressed format which is much smaller :)

Cheers,
-- 
Jérôme Kieffer
tel +33 476 882 445
