### ISSUE TITLE
Error while trying to open image. tostring() has been removed.

### ISSUE THREAD

**Issue by hhslepicka** [kif/fabio#44]
Hi,
I installed the latest version of FabIO from github master and the tests passed.
The issue is that I'm trying to use FabIO to open a TIFF image but the following error is shown:

```python
In [1]: import fabio

In [2]: fabio.open("Feb09-bright-00.300s_WAXS")

WARNING:tifimage:Unable to read Feb09-bright-00.300s_WAXS with TiffIO due to could not broadcast input array from shape (521,1042) into shape (1042,1042), trying PIL
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-ce38474c489e> in <module>()
----> 1 fabio.open("Feb09-bright-00.300s_WAXS")

/Users/hugoslepicka/anaconda/envs/pyXS/lib/python3.4/site-packages/fabio-0.3.0b3-py3.4-macosx-10.5-x86_64.egg/fabio/openimage.py in openimage(filename, frame)
    144         obj = _openimage(filename)
    145         logger.debug("Attempting to read frame %s from %s" % (frame, filename))
--> 146         obj = obj.read(obj.filename, frame)
    147     return obj
    148

/Users/hugoslepicka/anaconda/envs/pyXS/lib/python3.4/site-packages/fabio-0.3.0b3-py3.4-macosx-10.5-x86_64.egg/fabio/tifimage.py in read(self, fname, frame)
    188                         self.data = numpy.fromstring(self.pilimage.tostring(), PIL_TO_NUMPY[self.pilimage.mode])
    189                     else:  # probably RGB or RGBA images: rely on PIL to convert it to greyscale float.
--> 190                         self.data = numpy.fromstring(self.pilimage.convert("F").tostring(), numpy.float32)
    191                     self.data.shape = (self.dim2, self.dim1)
    192             else:

/Users/hugoslepicka/anaconda/envs/pyXS/lib/python3.4/site-packages/PIL/Image.py in tostring(self, *args, **kw)
    684     def tostring(self, *args, **kw):
    685         raise Exception("tostring() has been removed. " +
--> 686                         "Please call tobytes() instead.")
    687
    688     def tobitmap(self, name="image"):

Exception: tostring() has been removed. Please call tobytes() instead.
```

I can open the image with the following code:

```python


In [1]: from PIL import Image

In [2]: im = Image.open("Feb09-bright-00.300s_WAXS")

In [3]: import numpy as np

In [4]: import matplotlib.pyplot as plt

In [5]: data = np.asarray(im).copy()

In [6]: plt.imshow(data)

In [7]: plt.show()
```

Packages installed:
===============
python                    3.4.3
fabio                     0.3.0b3
pillow                    3.0.0

Thanks,
Hugo

**Comment by kif** [comment]
Hi Hugo,

Could you please provide me with such image, so that I can setup a non regression test ?

Thanks 
-- 
Jérôme Kieffer

**Comment by hhslepicka** [comment]
Hi Jérôme,
Sure, please download the image from the following link:
https://www.dropbox.com/s/toi5z2rknsx5qof/Feb09-bright-00.300s_WAXS?dl=0

**Comment by kif** [comment]
On Wed, 02 Dec 2015 07:32:03 -0800
Hugo Slepicka <notifications@github.com> wrote:

> Hi Jérôme,
> Sure, please download the image from the following link:
> https://www.dropbox.com/s/toi5z2rknsx5qof/Feb09-bright-00.300s_WAXS?dl=0

Thanks for the image.
The bug is deeper as neither TiffIO neither PIl are able to handle the image

Apparently your image is a Tiff 1042x1042, uint16 big-endian. Can you confirm that ?

-- 
Jérôme Kieffer

**Comment by hhslepicka** [comment]
Yes, the information is correct.
1042x1042 - uint16 - big-endian.

**Comment by hhslepicka** [comment]
Jérôme,

So far I went to the TiffIO.py and discovered that my image has what seems to be an incorrect value in the tag TAG_STRIP_BYTE_COUNTS. The value in this tag is half of what it is supposed to be, leading to this error when the library tries to assign the data to the numpy array.

**Comment by kif** [comment]
Hi Hugo,

I have the code almost fixed on the "PIL" side (which was poorly interfaced). TiffIO needs to be fixed as well but neither Thomas, not Armando are around before next week.
@vasole
@t20100 

For now I will create the non regression test.

Cheers,
 
Jerome

**Comment by vasole** [comment]
Not a TiffIO bug. The file provides wrong information as confirmed by Image Magick

I will try to implement a workaround with a warning as Image Magick does:

![fabio_bogus_strip_byte_counts](https://cloud.githubusercontent.com/assets/5636251/11553057/5a4b53f0-998b-11e5-91c5-b434f15fd48b.png)

Armando

**Comment by vasole** [comment]
Workaround in TiffIO implemented. Please update your copy.

@t20100
@kif

**Comment by kif** [comment]
closed: passes on windows, linux and MacOSX
