### ISSUE TITLE
PilatusImage str error on Python3

### ISSUE THREAD

**Issue by hhslepicka** [kif/fabio#46]
When trying to open an image using FabIO on Python 3 an error message is presented: 'str' does not support the buffer interface.

```python
In [1]: fname = "lysb_5mg-1.90s_SAXS"

In [2]: import fabio

In [3]: fabio.open(name)
```

The file can be downloaded from the following link: https://db.tt/FInF99Fz

**Comment by kif** [comment]
fixed
