### ISSUE TITLE
unexpected directory in the pip package

### ISSUE THREAD

**Issue by picca** [kif/fabio#49]
Hello, when I download the pacakge from pip, I get the pylint directory.

Is it possible to remove this directory from the sdource distribution.

Thanks

**Comment by picca** [comment]
There is also the generated documentation.
Is it possible to remove this from the source distribution.

**Comment by kif** [comment]
Hi Fred,
If you want a "debian" friendly tar-ball, why don't you  use "python setup.py debian_src" ?
It is important for the community to have the generated doc as part of the source package as not everyone has sphinx and all dependencies installed to generate the doc.

Cheers,

Jérôme
