### ISSUE TITLE
packaging for debian8 (Jessie)

### ISSUE THREAD

**Issue by criticanalytic** [kif/fabio#51]
automatic debian packaging for debian8 (Jessie) of the development version is 
currently not working. This can be fixed by squeezing the "third party
removal" patch from Fred. (see mailing list thread)

**Comment by kif** [comment]
related to #32

**Comment by kif** [comment]
there is still a bug in python3 resulting from the refactoring
affects cbfimage

**Comment by kif** [comment]
branch 0.4 is now merged under master
