### ISSUE TITLE
Profiling of CBF reading performances...

### ISSUE THREAD

**Issue by kif** [kif/fabio#52]
Requested by ID31 & ID15.

**Comment by kif** [comment]
the current values is (for 200 Pilatus 2M images):
Decompression byte ofset: 1.4s
MD5 sum: 0.7s
numpy.astype: 0.5s
total: 2.8s

Both astype and MD5 could be skipped when speed is really needed

**Comment by kif** [comment]
After simple optimization on reaches 1.8s. 
the byte_offset should ideally provide int32 (instead of int64 in the generic case) which would prevent the memcopy & cast

**Comment by jonwright** [comment]
Hi Jerome,

Vadim's code in cryio might be useful for doing a benchmarking 
comparison as it has already been optimized. It can be found at:
http://www.3lp.cx/cryio/

Back in November 2014 we saw:

In [23]: %timeit ret = cryio_cbfimage.CbfImage("run2_1_00148.cbf")
10 loops, best of 3: 29.8 ms per loop

In [25]: %timeit ret = fabio.open("run2_1_00148.cbf")
10 loops, best of 3: 150 ms per loop

I seem to remember that it was before some cif optimisations...

**Comment by kif** [comment]
After optimization, reading of 200 files takes 1.17s (0.93s for the decompression and 0.09s for the read itself) 


In [14]: %timeit fabio.cbfimage.CbfImage().read("run2_1_00148.cbf")
10 loops, best of 3: 20.7 ms per loop

%timeit fabio.cbfimage.CbfImage().read("run2_1_00148.cbf", check_MD5=False)
100 loops, best of 3: 12.4 ms per loop

**Comment by jonwright** [comment]
Hi

> Vadim's code in cryio might be useful for doing a benchmarking 
> comparison as it has already been optimized. It can be found at:
> http://www.3lp.cx/cryio/

It's http://hg.3lp.cx/cryio

> 
> Back in November 2014 we saw:
> 
> In [23]: %timeit ret = cryio_cbfimage.CbfImage("run2_1_00148.cbf")
> 10 loops, best of 3: 29.8 ms per loop
> 
> In [25]: %timeit ret = fabio.open("run2_1_00148.cbf")
> 10 loops, best of 3: 150 ms per loop

I may try to run the tests again, to compare it.

Vadim

**Comment by kif** [comment]
On Mon, 21 Mar 2016 10:35:28 -0700
Jon Wright <notifications@github.com> wrote:

> Hi
> 
> > Vadim's code in cryio might be useful for doing a benchmarking 
> > comparison as it has already been optimized. It can be found at:
> > http://www.3lp.cx/cryio/

To be fair, run the test on scisoft13 ...

now >90% of the time is spent in the "byte-offset decompression"
algorithm which we have checked to be at the same speed (in 2014).

Cheers,

Jerome
