### ISSUE TITLE
problem when trying to open an hdf5 file

### ISSUE THREAD

**Issue by picca** [kif/fabio#53]
Hello Jerome,

I get this error message

Traceback (most recent call last):
  File "/usr/bin/fabio_viewer", line 189, in open_h5_data_series
    entry = nxs.get_entries()[0]
  File "/usr/lib/python2.7/dist-packages/fabio/nexus.py", line 231, in get_entries
    self.h5[grp].attrs["NX_class"] == "NXentry")]
  File "/usr/lib/python2.7/dist-packages/fabio/nexus.py", line 143, in from_isotime
    return time.mktime(time.strptime(base, "%Y-%m-%dT%H:%M:%S")) + tz
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data "['2016-03-23T12:01:" does not match format '%Y-%m-%dT%H:%M:%S'

**Comment by picca** [comment]
the problem seems to be with the seconds

wait a minut the code contain this

def from_isotime(text, use_tz=False):
    """
    @param text: string representing the time is iso format
    """
    text = str(text)
    base = text[:19]
    if use_tz and len(text) == 25:
        sgn = 1 if  text[:19] == "+" else -1
        tz = 60 * (60 * int(text[20:22]) + int(text[23:25])) * sgn
    else:
        tz = 0
    return time.mktime(time.strptime(base, "%Y-%m-%dT%H:%M:%S")) + tz

but the len of the time data is ['2016-03-23T12:01: = 19
strange data format.

**Comment by picca** [comment]
Here the information taken from hdfview 
start_time (8760, 2)
    String, length = 24,    1
    Number of attributes = 1
        description = Starting time of measurement

the content is

2016-03-23T12:01:28+0100

**Comment by picca** [comment]
text before and after str(text)

['2016-03-23T12:01:28+0100']
['2016-03-23T12:01:28+0100']

This is an array of string

**Comment by picca** [comment]
In [1]: from dateutil.parser import parse

In [2]: parse('2016-03-23T12:01:28+0100')
datetime.datetime(2016, 3, 23, 12, 1, 28, tzinfo=tzoffset(None, 3600))

maybe the right things to do is to use datetime on the string

**Comment by picca** [comment]
When extracted with h5py, I get an array of string

In [8]: f['scan_27/start_time']
Out[8]: <HDF5 dataset "start_time": shape (1,), type "|S24">

but it seems that the value given to the from_isotime function is the string equivalent of the array

In [14]: str(f['scan_27/start_time'][:])
Out[14]: "['2016-03-23T12:01:28+0100']"

**Comment by kif** [comment]
Hi Fred, 
The problem comes from  the "start_time" which is not a string but an array of strings.
"['2016-03-23T12:01:28+0100']" is not '2016-03-23T12:01:28+0100'

Dateutil looks nice but it is an additional dependency ...
I will fix the issue in "nexus" directly
