### ISSUE TITLE
.f2d files?

### ISSUE THREAD

**Issue by Luindil** [kif/fabio#54]
Hei,

i have a user of Dioptas who has a lot of .f2d files. Do you plan to implement reading of the "Fit2d" file format into fabio?

You already support fit2dmaskimage, and fit2dspreadsheetimage.

I could not find any specifications online for the .f2d file format, but since you are close to hammersley, maybe you can get it from him.

Best wishes,
Clemens

**Comment by kif** [comment]
On Wed, 06 Apr 2016 00:32:04 -0700
Clemens Prescher <notifications@github.com> wrote:

> Hei,
> 
> i have a user of Dioptas who has a lot of .f2d files. Do you plan to implement reading of the "Fit2d" file format into fabio?

Hi Clemens,

How are you ?

> I could not find any specifications online for the .f2d file format, but since you are close to hammersley, maybe you can get it from him.

I can investigate a bit ...
Do you know what is in those files ? do you have some examples of the same data saved in this format + another format which is already supported by FabIO ?
This is to establish a unit-test and help development.

Cheers,

Jérôme

**Comment by Luindil** [comment]
Hei Jérôme,
I converted the 2 images in the test folder into f2d files, please find them attached. I have really no idea about the structure of the file and I could not find a specification in the Fit2d manual.

Best wishes,
Clemens
[f2d.zip](https://github.com/kif/fabio/files/207940/f2d.zip)

**Comment by kif** [comment]
Hi Clemens,

Apparently you used a "newer" version of fit2d which saves data by pages of 512. Elder versions apparently read pages of 2k but using only 512bytes of the 2k (this was probably a bug).

**Comment by kif** [comment]
can you try out this branch ...
https://github.com/kif/fabio/tree/issue_54

**Comment by kif** [comment]
fixed.
