### ISSUE TITLE
Princeton Instruments SPE files

### ISSUE THREAD

**Issue by Luindil** [kif/fabio#55]
Hei Jérôme,

I had some users who also collect diffraction data with Princeton Instrument Detectors. Since I already wrote a small library to open the version 2 and version 3 .spe formats. I know how to read the fileformat. Would you be interested that I add the file format it to the fabio library?

Best wishes,
Clemens

**Comment by kif** [comment]
Hi Clemens,

I will release a new version of FabIO in the comming weeks, could you send me your code to integrate it.
It would also be nice to have some testimages.

Cheers,

Jerome

**Comment by Luindil** [comment]
Hei Jerome,

should I do a small pull request, and try to convert it into fabio class format, or do you want to do it yourself?

my spe reading code is inclduded in 
https://github.com/Luindil/T-rax/blob/develop/t-rax/model/SpeFile.py

i have written some small tests in
https://github.com/Luindil/T-rax/blob/develop/t-rax/test/test_spe_file.py

and the test files are under:
https://github.com/Luindil/T-rax/tree/develop/t-rax/test/test_files

Best wishes,
Clemens

**Comment by kif** [comment]
On Tue, 28 Jun 2016 04:42:50 -0700
Clemens Prescher <notifications@github.com> wrote:

> Hei Jerome,
> 
> should I do a small pull request, and try to convert it into fabio class format, or do you want to do it yourself?
> 

It is up to you ...
I will release the next fabio early this summer to make a new release
of pyFAI by the end of the summer.

Cheers,

Jerome

**Comment by Luindil** [comment]
Hei Jerome,

i am on it. However I have a short organisational question: how do I run a single unittest without having to run all tests and needing to build the whole package again? I am used to a very short feedback cycle for Test-Driven Programming...

Best wishes,
Clemens

**Comment by kif** [comment]
replace testcbfimage with your test module. Here are a few examples:

python run_tests.py -i fabio.test.testcbfimage.suite #the whole suite
python run_tests.py -i fabio.test.testcbfimage #auto-discovery
python run_tests.py -i fabio.test.testcbfimage.TestCbfReader #only the class
python run_tests.py -i fabio.test.testcbfimage.TestCbfReader.test_unicode #only the method

**Comment by kif** [comment]
I will probably release next week...

**Comment by kif** [comment]
Hi Clemens,

I did the integration: it almost works. 
Do you have an idea of the "magic-bytes" of SPE ? it looks like a pure windows product and they may not have one (rely only on the extension?)
'''
for i in files:
    with open(i) as f:
        d=f.read(32)
    print(" ".join("%02x"%ord(j) for j in d),i)

00 00 01 00 00 00 3c 05 01 00 ec 51 38 3e 00 00 00 00 64 00 31 30 4d 61 79 32 30 31 33 00 00 00 v2_converted.SPE
00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 v3_2frames.spe
00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 64 00 00 00 00 00 00 00 00 00 00 00 00 00 v3.spe
00 00 00 00 00 00 f4 01 00 00 00 00 00 00 00 00 00 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 v3_custom_roi.spe
```
